# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of post', max_length=255)),
                ('image_url', models.TextField(help_text='Image url')),
                ('thumb_url', models.TextField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
