# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='authuser',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
