# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170408_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=256)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('fullname', models.CharField(blank=True, max_length=256, null=True)),
                ('guid', models.CharField(blank=True, max_length=256, null=True)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('token_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='credit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='medium_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Invalid'), (1, 'Pending'), (2, 'Published')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='dog', max_length=128, null=True),
        ),
    ]
