# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170409_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='access_level',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
